apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        - configMapRef:
            name: {{ .Values.xmsops }}            
        image: registry.cn-hangzhou.aliyuncs.com/inside/eureka:latest
        imagePullPolicy: IfNotPresent
        name: eureka
    {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- end }} 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
    {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
    {{- end }} 
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate