apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-storage-class
parameters:
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  monitors: 192.168.88.212:6789,192.168.88.213:6789,192.168.88.217:6789 
  pool: gumikube
  userId: gumikube
  userSecretName: ceph-secret-gumikube
  userSecretNamespace: default
provisioner: ceph.com/rbd
