apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: rms-admin-web
  namespace: fangjun
spec:
  rules:
  - host: rms-admin-web.fangjun.gumik8s.com
    http:
      paths:
      - backend:
          serviceName: rms-admin-web
          servicePort: 80
        path: /
  tls:
  - hosts:
    - rms-admin-web.fangjun.gumik8s.com
    secretName: ingress
