apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: gps-web
  namespace: stg
spec:
  rules:
  - host: gps-web.stg.gumik8s.com
    http:
      paths:
      - backend:
          serviceName: gps-web
          servicePort: 80
        path: /
  tls:
  - hosts:
    - gps-web.stg.gumik8s.com
    secretName: ingress
