apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"eureka"},"name":"eureka","namespace":"stg"},"spec":{"clusterIP":"None","ports":[{"name":"eureka","port":8761,"protocol":"TCP","targetPort":8761}],"selector":{"app":"eureka"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-11-18T07:19:38Z"
  labels:
    app: eureka
  name: eureka
  namespace: fangjun
  resourceVersion: "1812368"
  selfLink: /api/v1/namespaces/stg/services/eureka
  uid: 5c787253-6643-430c-98ea-493b2c2f61b1
spec:
  clusterIP: None
  ports:
  - name: eureka
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
