apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"rms-admin-web"},"name":"rms-admin-web","namespace":"stg"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"rms-admin-web"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-12-02T03:01:30Z"
  labels:
    app: rms-admin-web
  name: rms-admin-web
  namespace: fangjun
  resourceVersion: "4099956"
  selfLink: /api/v1/namespaces/stg/services/rms-admin-web
  uid: d3515603-b6d1-4df9-a45c-54311ee625d6
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rms-admin-web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
