apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wdms-frontend"},"name":"wdms-frontend","namespace":"stg"},"spec":{"ports":[{"name":"http","port":8407,"protocol":"TCP","targetPort":8407},{"name":"debug","port":18001,"protocol":"TCP","targetPort":18001}],"selector":{"app":"wdms-frontend"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-11-30T11:50:22Z"
  labels:
    app: wdms-frontend
  name: wdms-frontend
  namespace: fangjun
  resourceVersion: "3826377"
  selfLink: /api/v1/namespaces/stg/services/wdms-frontend
  uid: 8456b08d-bab0-44b5-b028-b5c1d3f63e9a
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8407
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: wdms-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
