apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  namespace: tools
  labels:
    app: openldap
spec:
  serviceName: openldap
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openldap
    spec:
      securityContext:
        fsGroup: 999
      terminationGracePeriodSeconds: 10
      containers:
        - name: openldap
          image: osixia/openldap:1.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 389
            - containerPort: 639
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
            - name: ladp-lib
              mountPath: /var/lib/ldap
            - name: ldap-conf
              mountPath: /etc/ldap/slapd.d
          livenessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 30
            timeoutSeconds: 20
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: ladp-lib
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storage-class
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: ldap-conf
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storage-class
      resources:
        requests:
          storage: 50Gi

