apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"guarantee-slip-cloud"},"name":"guarantee-slip-cloud","namespace":"stg"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"guarantee-slip-cloud"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"guarantee-slip-cloud"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"base"}}],"image":"registry.cn-hangzhou.aliyuncs.com/inside/stg-guarantee-slip-cloud:1","imagePullPolicy":"IfNotPresent","name":"guarantee-slip-cloud","resources":{"limits":{"cpu":"200m","memory":"1024Mi"},"requests":{"cpu":"200m","memory":"512Mi"}}}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"alihangzhou"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2019-11-30T12:59:54Z"
  generation: 5
  labels:
    app: guarantee-slip-cloud
  name: guarantee-slip-cloud
  namespace: stg
  resourceVersion: "4104046"
  selfLink: /apis/apps/v1/namespaces/stg/deployments/guarantee-slip-cloud
  uid: 4007b74c-c7f4-4d4c-9281-370f3be732f4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guarantee-slip-cloud
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guarantee-slip-cloud
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        image: registry.cn-hangzhou.aliyuncs.com/inside/guarantee-slip-cloud:latest
        imagePullPolicy: IfNotPresent
        name: guarantee-slip-cloud
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-30T13:21:30Z"
    lastUpdateTime: "2019-12-02T02:47:09Z"
    message: ReplicaSet "guarantee-slip-cloud-7f7dfd968c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-02T03:29:24Z"
    lastUpdateTime: "2019-12-02T03:29:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
