apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kibana-logging"},"name":"kibana-logging","namespace":"log"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"kibana-logging"}},"template":{"metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"k8s-app":"kibana-logging"}},"spec":{"containers":[{"env":[{"name":"ELASTICSEARCH_HOSTS","value":"http://elasticsearch-logging:9200"},{"name":"SERVER_NAME","value":"kibana-logging"},{"name":"SERVER_BASEPATH","value":"/kibana"},{"name":"SERVER_REWRITEBASEPATH","value":"true"}],"image":"registry.cn-hangzhou.aliyuncs.com/wanway-base/kibana-oss:7.2.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/kibana/api/status","port":"ui"},"initialDelaySeconds":5,"timeoutSeconds":10},"name":"kibana-logging","ports":[{"containerPort":5601,"name":"ui","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/kibana/api/status","port":"ui"},"initialDelaySeconds":5,"timeoutSeconds":10},"resources":{"limits":{"cpu":"1000m"},"requests":{"cpu":"100m"}}}],"imagePullSecrets":[{"name":"alihangzhou"}]}}}}
  creationTimestamp: "2019-11-21T02:39:11Z"
  generation: 9
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kibana-logging
  name: kibana-logging
  namespace: log
  resourceVersion: "3079533"
  selfLink: /apis/apps/v1/namespaces/log/deployments/kibana-logging
  uid: cdde6fca-409b-4739-b07f-2d9ad95375bc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kibana-logging
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-logging:9200
        - name: SERVER_NAME
          value: kibana-logging
        - name: SERVER_BASEPATH
          value: /kibana
        - name: SERVER_REWRITEBASEPATH
          value: "true"
        image: registry.cn-hangzhou.aliyuncs.com/wanway-base/kibana-oss:7.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /kibana/api/status
            port: ui
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /kibana/api/status
            port: ui
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-21T08:24:34Z"
    lastUpdateTime: "2019-11-22T02:43:15Z"
    message: ReplicaSet "kibana-logging-5c58cfcb75" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-26T04:06:38Z"
    lastUpdateTime: "2019-11-26T04:06:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
