apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"user2c-cloud"},"name":"user2c-cloud","namespace":"stg"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"user2c-cloud"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"user2c-cloud"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"base"}}],"image":"registry.cn-hangzhou.aliyuncs.com/inside/stg-user2c-cloud:1","imagePullPolicy":"IfNotPresent","name":"user2c-cloud","resources":{"limits":{"cpu":"200m","memory":"1024Mi"},"requests":{"cpu":"200m","memory":"512Mi"}}}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["master"],"ip":"192.168.88.244"},{"hostnames":["slave01"],"ip":"192.168.88.241"},{"hostnames":["slave02"],"ip":"192.168.88.242"},{"hostnames":["slave03"],"ip":"192.168.88.243"},{"hostnames":["slave04"],"ip":"192.168.88.245"}],"imagePullSecrets":[{"name":"alihangzhou"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2019-11-27T06:46:00Z"
  generation: 4
  labels:
    app: user2c-cloud
  name: user2c-cloud
  namespace: stg
  resourceVersion: "4101341"
  selfLink: /apis/apps/v1/namespaces/stg/deployments/user2c-cloud
  uid: 780d2879-afcc-4047-9071-697bc39f675e
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user2c-cloud
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user2c-cloud
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        image: registry.cn-hangzhou.aliyuncs.com/inside/stg-user2c-cloud:2
        imagePullPolicy: IfNotPresent
        name: user2c-cloud
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - master
        ip: 192.168.88.244
      - hostnames:
        - slave01
        ip: 192.168.88.241
      - hostnames:
        - slave02
        ip: 192.168.88.242
      - hostnames:
        - slave03
        ip: 192.168.88.243
      - hostnames:
        - slave04
        ip: 192.168.88.245
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-11-27T07:03:14Z"
    lastUpdateTime: "2019-11-27T07:03:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-27T07:03:12Z"
    lastUpdateTime: "2019-12-02T03:12:31Z"
    message: ReplicaSet "user2c-cloud-7875b8ff64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
