apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: monit
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  storageClassName: ceph-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
