apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: jenkins
  name: jenkins
  namespace: tools
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
