apiVersion: v1       
kind: Service        
metadata:
  annotations:       
  labels:
    app: openldap      
  name: openldap       
  namespace: tools   
spec:
  ports:
  - name: http       
    port: 389       
    targetPort: 389
  - name: https      
    port: 639      
    targetPort: 639
  selector:
    app: openldap   
