namespace: test
# 512,1024,1500
xmsops: xms512
hostAliases: 
- hostnames:
  - master
  ip: 192.168.88.244
- hostnames:
  - slave01
  ip: 192.168.88.241
- hostnames:
  - slave02
  ip: 192.168.88.242
- hostnames:
  - slave03
  ip: 192.168.88.243
- hostnames:
  - slave04
  ip: 192.168.88.245
resources:
  limits:
    cpu: 200m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 512Mi