apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.namespace }}-admin
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - 'pods'
  - 'pods/exec'
  verbs:
  - '*'