apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: {{ .Values.namespace }}-admin-rolebinding      
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io    
  kind: Role
  name: {{ .Values.namespace }}-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.namespace }}
  namespace: kube-system