apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rms-service"},"name":"rms-service","namespace":"stg"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"rms-service"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"rms-service"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"base"}}],"image":"registry.cn-hangzhou.aliyuncs.com/inside/stg-rms-service:7","imagePullPolicy":"IfNotPresent","name":"rms-service","resources":{"limits":{"cpu":"200m","memory":"1Gi"},"requests":{"cpu":"200m","memory":"512Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["master"],"ip":"192.168.88.244"},{"hostnames":["slave01"],"ip":"192.168.88.241"},{"hostnames":["slave02"],"ip":"192.168.88.242"},{"hostnames":["slave03"],"ip":"192.168.88.243"},{"hostnames":["slave04"],"ip":"192.168.88.245"}],"imagePullSecrets":[{"name":"alihangzhou"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2019-11-27T03:52:27Z"
  generation: 8
  labels:
    app: rms-service
  name: rms-service
  namespace: fangjun
  resourceVersion: "4105681"
  selfLink: /apis/apps/v1/namespaces/stg/deployments/rms-service
  uid: ea9f40f3-0ce0-4083-9d00-7204eb3f846a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rms-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rms-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        image: registry.cn-hangzhou.aliyuncs.com/inside/rms-service:latest
        imagePullPolicy: IfNotPresent
        name: rms-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - master
        ip: 192.168.88.244
      - hostnames:
        - slave01
        ip: 192.168.88.241
      - hostnames:
        - slave02
        ip: 192.168.88.242
      - hostnames:
        - slave03
        ip: 192.168.88.243
      - hostnames:
        - slave04
        ip: 192.168.88.245
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-27T05:51:11Z"
    lastUpdateTime: "2019-12-02T03:26:47Z"
    message: ReplicaSet "rms-service-755bccbbf8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-02T03:41:43Z"
    lastUpdateTime: "2019-12-02T03:41:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
