apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rms-admin-web"},"name":"rms-admin-web","namespace":"stg"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"rms-admin-web"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"rms-admin-web"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"base"}}],"image":"registry.cn-hangzhou.aliyuncs.com/inside/rms-admin-web:stg-1","imagePullPolicy":"IfNotPresent","name":"rms-admin-web"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"alihangzhou"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2019-12-02T02:21:32Z"
  generation: 6
  labels:
    app: rms-admin-web
  name: rms-admin-web
  namespace: fangjun
  resourceVersion: "4103480"
  selfLink: /apis/apps/v1/namespaces/stg/deployments/rms-admin-web
  uid: 8661673a-4506-41cb-be1f-2de330bb6a6b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rms-admin-web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rms-admin-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        image: registry.cn-hangzhou.aliyuncs.com/inside/rms-admin-web:latest
        imagePullPolicy: IfNotPresent
        name: rms-admin-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-02T02:55:05Z"
    lastUpdateTime: "2019-12-02T03:00:25Z"
    message: ReplicaSet "rms-admin-web-5855f67f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-02T03:26:29Z"
    lastUpdateTime: "2019-12-02T03:26:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
