apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"jenkins"},"name":"jenkins","namespace":"tools"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"serviceName":"jenkins","template":{"metadata":{"labels":{"app":"jenkins"}},"spec":{"containers":[{"image":"jenkinsci/blueocean:1.19.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"timeoutSeconds":5},"name":"jenkins","ports":[{"containerPort":8080},{"containerPort":50000}],"readinessProbe":{"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"timeoutSeconds":5},"resources":{"limits":{"cpu":1,"memory":"1Gi"},"requests":{"cpu":0.5,"memory":"500Mi"}},"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}],"securityContext":{"fsGroup":1000},"serviceAccountName":"jenkins","terminationGracePeriodSeconds":10}},"updateStrategy":{"type":"RollingUpdate"},"volumeClaimTemplates":[{"metadata":{"name":"jenkins-home"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"500Gi"}},"storageClassName":"ceph-storage-class"}}]}}
    podpreset.admission.kubernetes.io/podpreset-jenkins: resource version
  creationTimestamp: "2019-11-08T12:50:34Z"
  generation: 51
  labels:
    app: jenkins
  name: jenkins
  namespace: tools
  resourceVersion: "3584729"
  selfLink: /apis/apps/v1/namespaces/tools/statefulsets/jenkins
  uid: 55c83aa6-cb34-43ba-b787-3eb44a6bcc8f
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
  serviceName: jenkins
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        preset: jenkins
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: jenkins
        image: registry.cn-hangzhou.aliyuncs.com/wanway-base/jenkins:2.206
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: jenkins-home
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      storageClassName: ceph-storage-class
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentRevision: jenkins-869c8dc647
  observedGeneration: 51
  replicas: 0
  updateRevision: jenkins-869c8dc647
