apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: wdms-unified-web
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: wdms-unified-web.{{ .Values.namespace }}.gumik8s.com
    http:
      paths:
      - backend:
          serviceName: wdms-unified-web
          servicePort: 80
        path: /
  tls:
  - hosts:
    - wdms-unified-web.{{ .Values.namespace }}.gumik8s.com
    secretName: ingress
