apiVersion: v1
kind: Service
metadata:
  labels:
    app: common-city-service
  name: common-city-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8411
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: common-city-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
