apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: eureka
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
