apiVersion: v1
kind: Service
metadata:
  labels:
    app: guarantee-slip-cloud
  name: guarantee-slip-cloud
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8420
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: guarantee-slip-cloud
  sessionAffinity: None
  type: ClusterIP
