apiVersion: v1
kind: Service
metadata:
  labels:
    app: rms-web
  name: rms-web
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rms-web
  type: ClusterIP
