apiVersion: v1
kind: Service
metadata:
  labels:
    app: rms-service
  name: rms-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: rms-service
  type: ClusterIP
