apiVersion: v1
kind: Service
metadata:
  labels:
    app: wdms-frontend
  name: wdms-frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8407
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: wdms-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
