apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"rms-service"},"name":"rms-service","namespace":"stg"},"spec":{"ports":[{"name":"http","port":9800,"protocol":"TCP","targetPort":9800},{"name":"debug","port":19800,"protocol":"TCP","targetPort":19800}],"selector":{"app":"rms-service"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-11-30T11:12:01Z"
  labels:
    app: rms-service
  name: rms-service
  namespace: stg
  resourceVersion: "3825607"
  selfLink: /api/v1/namespaces/stg/services/rms-service
  uid: 2347a6de-081c-47ef-9065-955bb9214dda
spec:
  clusterIP: 10.2.137.237
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: rms-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
