apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wdms-frontend
  name: wdms-frontend
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wdms-frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wdms-frontend
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        - configMapRef:
            name: {{ .Values.xmsops }}            
        image: registry.cn-hangzhou.aliyuncs.com/inside/wdms-frontend:latest
        imagePullPolicy: IfNotPresent
        name: wdms-frontend
    {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- end }} 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
    {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
    {{- end }} 
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
