apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpldapadmin
  namespace: tools
  labels:
    app: phpldapadmin
spec:
  serviceName: phpldapadmin
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: openldap
        image: osixia/phpldapadmin:0.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 20
        name: phpldapadmin
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi 
          requests:
            cpu: 200m
            memory: 200Mi  
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1


