apiVersion: v1
kind: Service
metadata:
  labels:
    app: wdms-unified-web
  name: wdms-unified-web
  namespace: stg
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wdms-unified-web
  type: ClusterIP
