apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wdms-service"},"name":"wdms-service","namespace":"stg"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8408},{"name":"debug","port":18001,"protocol":"TCP","targetPort":18001}],"selector":{"app":"wdms-service"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-11-30T12:47:12Z"
  labels:
    app: wdms-service
  name: wdms-service
  namespace: stg
  resourceVersion: "3827605"
  selfLink: /api/v1/namespaces/stg/services/wdms-service
  uid: 90602e22-3a6a-45d4-9d2b-a899d4009ffb
spec:
  clusterIP: 10.2.94.3
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8408
  - name: debug
    port: 18001
    protocol: TCP
    targetPort: 18001
  selector:
    app: wdms-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
