apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: timezone
  namespace: tools
spec:
  selector:
    matchLabels:
      preset: timezone
  env:
  - name: TZ
    value: Asia/Shanghai
