apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-deploy-sts
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - patch
  - update
  
