apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wdms-frontend"},"name":"wdms-frontend","namespace":"stg"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"wdms-frontend"}},"strategy":{"rollingUpdate":{"maxSurge":"50%","maxUnavailable":"50%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"wdms-frontend"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"base"}}],"image":"registry.cn-hangzhou.aliyuncs.com/inside/stg-wdms-frontend:1","imagePullPolicy":"IfNotPresent","name":"wdms-frontend","resources":{"limits":{"cpu":"200m","memory":"1024Mi"},"requests":{"cpu":"200m","memory":"512Mi"}}}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"alihangzhou"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2019-11-26T10:22:22Z"
  generation: 5
  labels:
    app: wdms-frontend
  name: wdms-frontend
  namespace: fangjun
  resourceVersion: "4104474"
  selfLink: /apis/apps/v1/namespaces/stg/deployments/wdms-frontend
  uid: 54f38454-282d-4734-84b0-aba185ba908c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wdms-frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wdms-frontend
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: base
        image: registry.cn-hangzhou.aliyuncs.com/inside/wdms-frontend:stg-1
        imagePullPolicy: IfNotPresent
        name: wdms-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihangzhou
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-02T03:29:25Z"
    lastUpdateTime: "2019-12-02T03:29:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-11-27T03:46:34Z"
    lastUpdateTime: "2019-12-02T03:32:31Z"
    message: ReplicaSet "wdms-frontend-dd86d5cc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
