apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: jenkins
  namespace: tools
spec:
  rules:
  - host: jenkins.gumik8s.com
    http:
      paths:
      - path: /jenkins
        backend:
          serviceName: jenkins
          servicePort: 8080
  tls:
  - hosts:
    - jenkins.gumik8s.com
    secretName: ingress
