apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: tools
  namespace: tools
spec:
  rules:
  - host: jenkins.gumik8s.com
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
        path: /
  - host: openldap.gumik8s.com
    http:
      paths:
      - backend:
          serviceName: openldap
          servicePort: 389
        path: /
  tls:
  - hosts:
    - jenkins.gumik8s.com
    - openldap.gumik8s.com
    secretName: ingress
