apiVersion: v1
data:
  EUREKA_SERVER: http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/,http://eureka-2.eureka:8761/eureka/
  PORT: "8761"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"EUREKA_SERVER":"http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/,http://eureka-2.eureka:8761/eureka/","PORT":"8761"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"eureka","namespace":"stg"}}
  creationTimestamp: "2019-10-17T03:17:44Z"
  name: eureka
  namespace: stg
  resourceVersion: "121934"
  selfLink: /api/v1/namespaces/stg/configmaps/eureka
  uid: af6a9b21-f08c-11e9-9aa7-000c29a6fbeb
