apiVersion: v1
data:
  COMMON-CITY-SERVICE: http://common-city-service.{{ .Values.namespace }}
  EUREKA_SERVER: http://eureka-0.eureka.{{ .Values.namespace }}:8761/eureka/,http://eureka-1.eureka.{{ .Values.namespace }}:8761/eureka/,http://eureka-2.eureka.{{ .Values.namespace }}:8761/eureka/
  EUREKA_PORT: "8761"
  NAMESPACE:  {{ .Values.namespace }}
kind: ConfigMap
metadata:
  name: base
  namespace: {{ .Values.namespace }}